[package]
name = "wxrust-config"
version = "0.0.1-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
vendored = []

[dependencies]
cc = "1.0.72"
