name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-wx30gtk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Prerequisites
      run: sudo apt install libwxgtk3.0-gtk3-dev
    - name: Check fmt
      run: cargo fmt --check --all
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-wx32gtk:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Prerequisites
      run: |
        sudo apt-key adv --fetch-keys https://repos.codelite.org/CodeLite.asc
        sudo apt-add-repository 'deb https://repos.codelite.org/wx3.2.0/ubuntu/ focal universe'
        sudo apt update
        sudo apt install libwxgtk3.2unofficial-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-mac:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Prerequisites
      run: rm '/usr/local/bin/2to3' && brew update && brew install wxwidgets || true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-vendored-mac:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    # - name: Install Prerequisites
    #   run: brew install wxwidgets
    - name: Build
      run: cargo build --verbose --features vendored
    - name: Run tests
      run: cargo test --verbose --features vendored

  build-vendored-mingw64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Prerequisites
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --verbose --features vendored --target x86_64-pc-windows-gnu
    # Disable tests until wx target test failure fixed to add some useful unit test
    # - name: Run tests
    #   run: cargo test --verbose --features vendored --target x86_64-pc-windows-gnu

  build-vendored-msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose --features vendored
    # Disable tests until copying DLLs to target folder to be implemented
    # - name: Run tests
    #   run: cargo test --verbose --features vendored
